### ISSUE TITLE
Event machine not initialized

### ISSUE THREAD

**Issue by binford2k** [gruis/sinatra-websocket#10]
Using the sample code, everything works fine until I press ctrl-c to stop it as directed. At that point it terminates by stack tracing.

> binford2k:websockets ben$ ruby ws.rb
> == Sinatra/1.4.4 has taken the stage on 4567 for development with backup from Thin
> Thin web server (v1.6.1 codename Death Proof)
> Maximum connections set to 1024
> Listening on localhost:4567, CTRL+C to stop
> 127.0.0.1 - - [06/Nov/2013 01:24:04] "GET / HTTP/1.1" 200 1138 0.0077
> ^CStopping ...
> wetbsocket closed
> Stopping ...
> /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
>     from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in`close_connection'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `block in stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in`each_value'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/server.rb:190:in`stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1406:in `quit!'
>     from /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1431:in`run!'
>     from /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
> Stopping ...
> /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in`close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
>     from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in`block in stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `each_value'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in`stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/thin-1.6.1/lib/thin/server.rb:190:in `stop!'
>     from /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1406:in`quit!'
>     from /Library/Ruby/Gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1505:in `block in setup_traps'

**Comment by gruis** [comment]
So you'd prefer to not see the stack trace?

**Comment by binford2k** [comment]
Well, I suppose that's one way of putting it. If this is normal behavior then it should be rescued so that users of my app don't freak out when they see "something break". Not attempting to call methods of an uninitialized object would probably be a better solution...

**Comment by mattmeng** [comment]
I'm running into the same issue.  I can hack it to rescue the exception, but I'd rather it not throw the exception in the first place.  Thanks for your hard work on this awesome gem!

``` bash
Stopping ...
/home/matt/.rvm/gems/ruby-2.1.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:95:in `block in stop!'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:95:in `each_value'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/thin-1.6.2/lib/thin/backends/base.rb:95:in `stop!'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/thin-1.6.2/lib/thin/server.rb:190:in `stop!'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1415:in `quit!'
    from /home/matt/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1514:in `block in setup_traps'
```

**Comment by jjacquay712** [comment]
I'm experiencing this issue also. The exception can cause issues when using https://github.com/larsch/ocra to package an app.

**Comment by gruis** [comment]
Ok, thanks for pointing out the issue and bumping it. I'll see if I can resolve it sometime soon. In the meantime, if anyone has a pull request to address it, I'll be happy to merge it.

**Comment by alejandrod** [comment]
Same problem over here! I don't quite understand how this all works. So, it's difficult to help

**Comment by gruis** [comment]
Ok, looks like the exception is raised only when there are connected clients. The stack trace doesn't show anything from sinatra-websocket, but given that we're using EventMachine it could still easily be in, or should be handled by, the sinatra-websocket code.

``` shell
$ ruby echo.rb
== Sinatra/1.4.5 has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.1 codename Death Proof)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
^CStopping ...
Stopping ...
== Sinatra has ended his set (crowd applauds)
```

``` shell
$ ruby echo.rb
== Sinatra/1.4.5 has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.1 codename Death Proof)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
127.0.0.1 - - [01/Dec/2014 11:16:18] "GET / HTTP/1.1" 200 1137 0.0034
127.0.0.1 - - [01/Dec/2014 11:16:18] "GET /favicon.ico HTTP/1.1" 404 448 0.0006
^CStopping ...
websocket closed
Stopping ...
/Users/caleb/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `block in stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `each_value'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/server.rb:190:in `stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/base.rb:1415:in `quit!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/base.rb:1440:in `run!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/main.rb:25:in `block in <module:Sinatra>'
Stopping ...
/Users/caleb/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection': eventmachine not initialized: evma_close_connection (RuntimeError)
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/eventmachine-1.0.3/lib/em/connection.rb:266:in `close_connection'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `block in stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `each_value'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/backends/base.rb:95:in `stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/thin-1.6.1/lib/thin/server.rb:190:in `stop!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/base.rb:1415:in `quit!'
        from /Users/caleb/.rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/base.rb:1514:in `block in setup_traps'
```

**Comment by gruis** [comment]
Try 88cc207 and let me know if it fixes your issues. If so, I'll package it and push a new release.

**Comment by binford2k** [comment]
Whoohoo! That's it, thanks for the fix!

**Comment by gruis** [comment]
New gem: https://rubygems.org/gems/sinatra-websocket/versions/0.3.1. It also prevents using Thin 2.0.0; see #12.

**Comment by jjacquay712** [comment]
Thanks for the fix, you're the man!

**Comment by alejandrod** [comment]
it works! thanks!!!!
